// --------------------------------------------------------------------------------------------
// Filename: stage-main.ks
// --------------------------------------------------------------------------------------------
// KOS Scripts for KSP to be used on SpaceX-RO-Falcons Mod (Pmborg RO Version) 
// --------------------------------------------------------------------------------------------
// Code by : Pmborg - https://forum.kerbalspaceprogram.com/index.php?/profile/198861-pmborg/
// Beta load from: 	- https://www.dropbox.com/sh/jd1oh6d806iyat1/AABa7aXbiYDfv8G-aQ4MyR-ta?dl=0
// Latest Download: - https://github.com/pmborg/SpaceX-RO-Falcons
// Purpose: 
//              This file is to allow Final USER to do some customizations at flight profile.
// 21/Dez/2020
// --------------------------------------------------------------------------------------------

// USER CAN SELECT:
declare global STAGE1_LAND_ON to "LAND". // "LAND" OR "SEA"
